<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Lenovo-PC" name="Default test" tests="1" failures="0" timestamp="20 Sep 2016 06:08:42 GMT" time="6.821" errors="0">
  <testcase name="@BeforeTest setUpMethod" time="0.0" classname="loginTS.LoginWithValidData">
    <failure type="java.lang.NoClassDefFoundError" message="org/apache/poi/ss/usermodel/Cell">
      <![CDATA[java.lang.NoClassDefFoundError: org/apache/poi/ss/usermodel/Cell
	at utility.DataProviderClass.setUp(DataProviderClass.java:15)
	at loginTS.LoginWithValidData.setUpMethod(LoginWithValidData.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:616)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
Caused by: java.lang.ClassNotFoundException: org.apache.poi.ss.usermodel.Cell
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 24 more
]]>
    </failure>
  </testcase> <!-- @BeforeTest setUpMethod -->
  <testcase name="@AfterTest tearDown" time="0.0" classname="loginTS.LoginWithValidData">
    <skipped/>
  </testcase> <!-- @AfterTest tearDown -->
  <testcase name="LoginWithValid" time="0.0" classname="loginTS.LoginWithValidData">
    <skipped/>
  </testcase> <!-- LoginWithValid -->
</testsuite> <!-- Default test -->
